version: '3'

services:

  web:
    image: python:3-alpine
    command: python3 manage.py runserver 8000
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
    depends_on:
      - backend
      - broker
      - worker

  backend:
    image: redis:alpine
    ports:
      - '6379'

  broker:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '8080:15672'

  worker:
    build: celery.Dockerfile
    command: celery -A proj beat -l info
    working_dir: /app
    volumes:
      - './WorkCentre:/app'
