version: '3'

services:

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - '6969:8000'
    volumes:
      - '.:/app'
    depends_on:
      - backend
      - broker
      - worker

  backend:
    image: redis:alpine
    ports:
      - '6379'

  broker:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '8080:15672'

  worker:
    build:
      context: .
      dockerfile: celery.Dockerfile
    entrypoint: ""
    command: celery -A WorkCentre worker -l info --concurrency 10
    working_dir: /app
    volumes:
      - '.:/app'

  monitor:
    build:
      context: .
      dockerfile: celery.Dockerfile
    entrypoint: ""
    command: celery -A WorkCentre flower
    ports:
      - '5555:5555'
    working_dir: /app
    volumes:
    - '.:/app'