version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
      DOCKER: 'True'
    ports:
      - '6969:8000'
    volumes:
      - '.:/app'
    depends_on:
      - backend
      - worker

  backend:
    image: redis:alpine
    ports:
      - '6379:6379'

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ""
    command: celery -A WorkCentre worker -l INFO --concurrency 10
    working_dir: /app
    volumes:
      - '.:/app'

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ""
    command: celery -A WorkCentre flower
    ports:
      - '5555:5555'
    working_dir: /app
    volumes:
    - '.:/app'